CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(64) PRIMARY KEY,
  feishu_open_id VARCHAR(128) UNIQUE,
  feishu_union_id VARCHAR(128) UNIQUE,
  name VARCHAR(128) NOT NULL,
  department VARCHAR(128) NOT NULL DEFAULT '',
  avatar_url TEXT,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS role_assignments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(64) NOT NULL,
  role VARCHAR(32) NOT NULL,
  source VARCHAR(64) NOT NULL DEFAULT 'admin',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_role_user_role (user_id, role),
  CONSTRAINT fk_role_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trainees (
  id VARCHAR(96) PRIMARY KEY,
  name VARCHAR(128) NOT NULL DEFAULT '',
  roman_name VARCHAR(128) NOT NULL DEFAULT '',
  department VARCHAR(128) NOT NULL DEFAULT '',
  department_en VARCHAR(128) NOT NULL DEFAULT '',
  sentence TEXT,
  sort_order INT NOT NULL DEFAULT 0,
  profile_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS teams (
  id VARCHAR(96) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  track_code VARCHAR(32) NOT NULL DEFAULT '',
  track_name VARCHAR(128) NOT NULL DEFAULT '',
  project VARCHAR(255) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'open',
  capacity INT NOT NULL DEFAULT 5,
  sort_order INT NOT NULL DEFAULT 0,
  meta_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  team_id VARCHAR(96) NOT NULL,
  user_id VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL DEFAULT '',
  department VARCHAR(128) NOT NULL DEFAULT '',
  role_key VARCHAR(64) NULL,
  duty VARCHAR(128) NOT NULL DEFAULT '',
  role VARCHAR(128) NOT NULL DEFAULT '',
  photo_url TEXT,
  is_advisor BOOLEAN NOT NULL DEFAULT FALSE,
  joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_team_member_user (team_id, user_id),
  UNIQUE KEY uq_team_member_role (team_id, role_key),
  CONSTRAINT fk_member_team FOREIGN KEY (team_id) REFERENCES teams(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS works (
  id VARCHAR(96) PRIMARY KEY,
  team_id VARCHAR(96) NOT NULL,
  team_name VARCHAR(128) NOT NULL DEFAULT '',
  project VARCHAR(255) NOT NULL,
  pitch TEXT,
  stack_json JSON NOT NULL,
  demo_url TEXT,
  code_url TEXT,
  doc_url TEXT,
  screenshots_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'submitted',
  submitted_by VARCHAR(64) NOT NULL DEFAULT '',
  submitted_at TIMESTAMP NULL,
  reviewed_by VARCHAR(64) NOT NULL DEFAULT '',
  reviewed_at TIMESTAMP NULL,
  review_note TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_works_team (team_id),
  KEY idx_works_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vote_windows (
  id VARCHAR(64) PRIMARY KEY,
  status VARCHAR(32) NOT NULL DEFAULT 'voting',
  window_label VARCHAR(128) NOT NULL DEFAULT '投票窗口开启中',
  point_scale_json JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS votes (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  voter_id VARCHAR(64) NOT NULL,
  team_id VARCHAR(96) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  source VARCHAR(64) NOT NULL DEFAULT 'web',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_active_vote (voter_id, status),
  KEY idx_votes_team (team_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS judge_scores (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  judge_id VARCHAR(64) NOT NULL,
  team_id VARCHAR(96) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  score_json JSON NOT NULL,
  total_score DECIMAL(6,2) NULL,
  comment TEXT,
  submitted_at TIMESTAMP NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_judge_team_score (judge_id, team_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS event_stages (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  subtitle VARCHAR(255) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  display_time TEXT,
  sort_order INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bigscreen_state (
  id VARCHAR(64) PRIMARY KEY,
  screen_key VARCHAR(64) NOT NULL,
  view_name VARCHAR(64) NOT NULL,
  params_json JSON NOT NULL,
  pushed_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS roadshow_sessions (
  id VARCHAR(64) PRIMARY KEY,
  current_team_id VARCHAR(96) NOT NULL DEFAULT '',
  next_team_id VARCHAR(96) NOT NULL DEFAULT '',
  phase VARCHAR(64) NOT NULL DEFAULT 'DEMO',
  started_at DATETIME NULL,
  duration_ms INT NOT NULL DEFAULT 900000,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mission_countdowns (
  id VARCHAR(64) PRIMARY KEY,
  started_at DATETIME NULL,
  duration_ms INT NOT NULL DEFAULT 86400000,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS result_snapshots (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  status VARCHAR(32) NOT NULL DEFAULT 'published',
  point_scale_json JSON NOT NULL,
  result_json JSON NOT NULL,
  published_by VARCHAR(64) NOT NULL DEFAULT '',
  published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  actor VARCHAR(64) NOT NULL DEFAULT '',
  action VARCHAR(128) NOT NULL,
  target_type VARCHAR(64) NOT NULL DEFAULT '',
  target_id VARCHAR(128) NOT NULL DEFAULT '',
  message TEXT,
  before_json JSON NULL,
  after_json JSON NULL,
  ip VARCHAR(64) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_audit_action (action),
  KEY idx_audit_target (target_type, target_id),
  KEY idx_audit_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_sessions (
  id VARCHAR(64) PRIMARY KEY,
  role VARCHAR(32) NOT NULL,
  user_id VARCHAR(96) NOT NULL DEFAULT '',
  source VARCHAR(64) NOT NULL DEFAULT '',
  session_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_auth_sessions_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS oauth_states (
  state VARCHAR(64) PRIMARY KEY,
  provider VARCHAR(32) NOT NULL DEFAULT 'feishu',
  redirect_path VARCHAR(255) NOT NULL DEFAULT '/site.html#me',
  redirect_uri VARCHAR(512) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NOT NULL,
  KEY idx_oauth_states_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
